import assert from 'node:assert/strict';
import test from 'node:test';
import { createCatalog, defineComponentDoc, definePatternDoc, searchCatalog, stableStringify, validateCatalog } from '../src/index.ts';
const button = defineComponentDoc({ schemaVersion:1, kind:'component', id:'ui.button', name:'Button', package:'@commonspace/ui', version:'0.2.0', status:'stable', category:'action', summary:'Triggers an immediate action.', sourcePath:'packages/ui/src/button/button.tsx', entrypoints:['@commonspace/ui/button'], keywords:['action','submit'], useWhen:['The user can act.'], avoidWhen:['The target is navigation.'], tokens:['--cs-accent'], related:[], stories:['catalog-ui--button'], accessibility:{requirements:['Keep a stable name.']}, props:[{name:'variant',type:'string',required:false}], variants:[{name:'primary',guidance:'Use once.'}], states:['default'], examples:{preferred:[],avoid:[]} });
const pattern = definePatternDoc({ schemaVersion:1, kind:'pattern', id:'pattern.form-actions', name:'Form actions', version:'0.2.0', status:'stable', summary:'Orders actions.', keywords:['form','submit'], useWhen:['A form completes.'], avoidWhen:['No input exists.'], components:['ui.button'], anatomy:['Fields','Actions'], states:['idle','pending'], responsive:['Stack narrowly.'], accessibility:{requirements:['Focus invalid fields.']}, examples:{preferred:[],avoid:[]} });
test('stable JSON sorts objects and preserves arrays',()=>assert.equal(stableStringify({z:1,a:{y:2,b:3},list:[{d:4,c:5}]}),'{\n  "a": {\n    "b": 3,\n    "y": 2\n  },\n  "list": [\n    {\n      "c": 5,\n      "d": 4\n    }\n  ],\n  "z": 1\n}\n'));
test('catalog sorting and search are deterministic',()=>{const catalog=createCatalog([pattern,button]);assert.deepEqual(catalog.entries.map((e)=>e.id),['pattern.form-actions','ui.button']);assert.equal(searchCatalog(catalog,'submit')[0]?.id,'ui.button');});
test('duplicate ids and broken references are rejected',()=>{assert.match(validateCatalog(createCatalog([button,{...button}])).map((i)=>i.message).join('\n'),/duplicate/i);assert.match(validateCatalog(createCatalog([{...pattern,components:['ui.missing']}])).map((i)=>i.message).join('\n'),/unknown component/i);});
test('unsafe metadata fails fast',()=>{assert.throws(()=>defineComponentDoc({...button,id:'Button'}),/id/i);assert.throws(()=>defineComponentDoc({...button,sourcePath:'../../secret'}),/sourcePath/i);});
