export { extractComponentApi, extractExportedInterfaces } from './source-api.ts';
export type { ExtractedComponentApi, ExtractedInterface, InterfacePickReference } from './source-api.ts';
export { createCatalog, getCatalogEntry, validateCatalog } from './catalog.ts';
export type { CreateCatalogOptions } from './catalog.ts';
export { searchCatalog, searchCatalogDetailed } from './search.ts';
export type { DetailedSearchResult, SearchBenchmark, SearchDiagnostic, SearchDiagnosticCode, SearchOptions } from './search.ts';
export { CatalogCompatibilityError, dependencyClosedPackageSets, selectCatalogVersion } from './compatibility.ts';
export { defineComponentDoc, defineMigrationDoc, definePatternDoc, defineTemplateDoc } from './define.ts';
export { stableStringify } from './stable-json.ts';
export { generateAgentDocumentSet, generateComponentMarkdown, generateDesignMarkdown, generateLlmsFiles, generatePatternMarkdown } from './generators.ts';
export type { GeneratedTextFile } from './generators.ts';
export { bundledCatalog } from './generated/catalog.ts';
export { bundledCompatibilityManifest } from './generated/compatibility.ts';
export type { AccessibilityDoc, CatalogIssue, CodeExample, CompatibilityManifest, CompatibilityRelease, ComponentDoc, ExampleSet, KnowledgeCatalog, KnowledgeEntry, KnowledgeKind, KnowledgeStatus, MigrationChange, MigrationDoc, PatternDoc, PropDoc, SearchResult, TemplateDoc, TemplateFileDoc, VariantDoc } from './types.ts';
