export { extractComponentApi, extractExportedInterfaces } from './source-api.ts';
export type { ExtractedComponentApi, ExtractedInterface, InterfacePickReference } from './source-api.ts';
export { createCatalog, getCatalogEntry, searchCatalog, validateCatalog } from './catalog.ts';
export type { CreateCatalogOptions } from './catalog.ts';
export { defineComponentDoc, defineMigrationDoc, definePatternDoc, defineTemplateDoc } from './define.ts';
export { stableStringify } from './stable-json.ts';
export { generateAgentDocumentSet, generateComponentMarkdown, generateDesignMarkdown, generateLlmsFiles, generatePatternMarkdown } from './generators.ts';
export type { GeneratedTextFile } from './generators.ts';
export { bundledCatalog } from './generated/catalog.ts';
export type { AccessibilityDoc, CatalogIssue, CodeExample, ComponentDoc, ExampleSet, KnowledgeCatalog, KnowledgeEntry, KnowledgeKind, KnowledgeStatus, MigrationChange, MigrationDoc, PatternDoc, PropDoc, SearchResult, TemplateDoc, TemplateFileDoc, VariantDoc } from './types.ts';
